# Generated by Django 4.2.7 on 2024-10-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMSP', models.BooleanField(verbose_name='Находится в реестре МСП')),
                ('companySile', models.CharField(max_length=100, verbose_name='Размер компании')),
                ('cityActual', models.CharField(max_length=100, verbose_name='Фактический город')),
                ('cityLegal', models.CharField(max_length=100, verbose_name='Юридический город')),
                ('OKVED2Name', models.CharField(max_length=255, verbose_name='ОКВЭД2. Наименование')),
                ('livingChance', models.FloatField(verbose_name='Шанс ухода')),
            ],
        ),
    ]
