# Generated by Django 4.2.7 on 2024-10-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='companySile',
            new_name='companySize',
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
