# Generated by Django 4.2.7 on 2024-10-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0002_rename_companysile_client_companysize_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='livingChance',
            new_name='leavingChance',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cityActual',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cityLegal',
        ),
        migrations.RemoveField(
            model_name='client',
            name='companySize',
        ),
        migrations.RemoveField(
            model_name='client',
            name='isMSP',
        ),
    ]
